name: build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm install

    - run: npm run build

    - uses: markwilson/html2pdf@v1.0
      with:
        htmlPath: build/index.html
        pdfName: build/register.pdf

    - name: Upload the PDF as an artifact
      id: pdf-artifact
      iif: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: register
        path: build/register.pdf
    
    - name: Add artifact links to the pull request
      if: github.event_name == 'pull_request' && steps.finder
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Rendered register: <${{ steps.pdf-artifact.outputs.artifact-url}}>

    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref_name == github.event.repository.default_branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build